# Generated by Django 5.0.8 on 2024-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventlink", "0002_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="days_of_week_availability",
        ),
        migrations.AddField(
            model_name="user",
            name="days_availability",
            field=models.CharField(
                default="Monday, Tuesday, Wednesday", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="time_range_availability",
            field=models.CharField(default="09:00 - 17:00", max_length=100),
        ),
    ]
