# Generated by Django 5.0.8 on 2024-08-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventlink", "0003_remove_user_days_of_week_availability_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="time_range_availability",
        ),
        migrations.AddField(
            model_name="user",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="days_availability",
            field=models.JSONField(default=dict),
        ),
    ]
