# Generated by Django 5.0.8 on 2024-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "eventlink",
            "0004_remove_user_time_range_availability_user_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="place",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
