# Generated by Django 5.0.8 on 2024-08-13 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eventlink", "0005_user_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="place",
        ),
    ]
