# Generated by Django 5.0.8 on 2024-08-14 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventlink", "0006_remove_event_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="days_availability",
        ),
        migrations.RemoveField(
            model_name="user",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="user",
            name="initial_time",
        ),
        migrations.CreateModel(
            name="AvailabilityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_availability", models.JSONField(default=list)),
                ("initial_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("event_duration", models.DurationField()),
                ("max_days_ahead", models.PositiveIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
