# Generated by Django 5.0.8 on 2024-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "eventlink",
            "0007_remove_user_days_availability_remove_user_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilityconfig",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="availabilityconfig",
            name="initial_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
