# Generated by Django 5.0.8 on 2024-08-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventlink", "0008_alter_availabilityconfig_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="place",
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
