# Generated by Django 5.0.8 on 2024-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventlink", "0009_remove_user_place_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
